modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/CyclopsMC/CyclopsCore/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cyclops-core"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="cyclopscore"
version="${file.jarVersion}"
displayName="Cyclops Core"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/cyclops-core.json"
description='''
Coremod for Integrated Dynamics, EvilCraft and others.
'''
[[dependencies.cyclopscore]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cyclopscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,]"
    ordering="NONE"
    side="BOTH"
