modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/CyclopsCore/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cyclops-core"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="cyclopscore"
version="${file.jarVersion}"
displayName="Cyclops Core"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/cyclops-core.json"
description='''
Coremod for Integrated Dynamics, EvilCraft and others.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.cyclopscore]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cyclopscore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
